- name: install pkgs
  apt:
    update_cache: yes
    name        :
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg2
      - software-properties-common
- name   : Add an Apt signing key, uses whichever key is at the URL
  apt_key:
    url  : https://download.docker.com/linux/debian/gpg
    state: present
- name: add docker repo
  apt_repository:
    repo : deb [arch=amd64] https://download.docker.com/linux/debian stretch stable
    state: present
- name: install pkgs
  apt :
    update_cache: yes
    name        :
    - docker-ce
    - docker-ce-cli
    - containerd.io