- name : build web
  shell: |
    cd /vagrant/suzen_website && \
    docker build -t 127.0.0.1:5000/suzenescape/web . && \
    docker push 127.0.0.1:5000/suzenescape/web
  when: vagrant|bool == true

- name    : copy web service file
  template:
    src  : web.service.j2
    dest : /etc/systemd/system/web.service
    owner: root
    group: root
    mode : 0644
  notify  : reload systemd
  register: service_file

- name   : Restart service
  service: name=web state=restarted
  when   : service_file.changed

- name   : Start service
  service: name=web state=started enabled=yes