---
admins:
  - name: aromanchev
    key:  "ssh-rsa "AAAAB3NzaC1yc2EAAAADAQABAAABAQDq1pJPTMxCFoeZODpHgMJKRfGqPQU7EnjytmUwcPJx8idzeJwBYayvZlvWQv/os9eAsZXw1pH2zj3LH7OXfxMGiqSu66QVDjNJ44ikB62T8p2NdM9/4VWUdcAp18M1CVy5VzqDS62B+scBXr9Fk3qocv55JXF9rS+27TU28xXEDGjBaUV4B5UfjpAcfnWyxEtplMyZyHgKYYjvpemnaDA/RSOp40sAEmlztGEArHcbrrq0CP62K1/M2rVx6M1M9TyyNtbNIM43qkptqcPSIXVDOTVyqlaXu70/F4uQLY+kT4T61x/8gNIj1bYrPqtgDri79SQ3DSjnZMeT3jPR0X/j""
  - name: bykva
    key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDWDDm3FFVvvV5rkecmGXAmOokKyD1JC6VnQv0T7RQgW9SQzamxFv+KzuxAsGRmDT+yTHUxRrBXIw+DDMJ77yTib1b64rOJOBEChErXvXxbkNY3ukSS+xB4aUcAUH6iq5dx/beqrvl/rz9jDY+6xDSaGQ5CMtYIc1qyO+jiMw0Npo8p5ghX+qiHQPFjpKISwb5k6z2vDvWkZQYb7d1oyZE1kceoKBST8pDB79JNE6+Uuy4KkkXbTBl13ovO0/LJRr/s2sr9N22PM5rK8HclduEyXRxHRDWiv9to+WsEzL36dzBj3oBGMxYqA2dzSG03zwFD/KDyFwuC9Ztypzy364Al"
