---
- hosts       : all
  gather_facts: no
  become      : true
  vars_files  :
    - vars.yaml

  pre_tasks:
  - name: intall python
    raw: apt -y update && apt install -y python-minimal python-apt
  - name: determine if registry is already installed
    uri:
      url: "http://{{ registry_url }}"
      return_content: yes
      timeout: 5
    register: result
    ignore_errors: yes

  - name: if running first time
    debug:
      msg: "THIS IS FIRST TIME RUNNING. RE-RUN vagrant provision after uploading tasks to registry"
    when: "result.status == -1"

  roles       :
    - install_docker
    - registry
    - { role: deploy_tasks, when: "result.status != -1", tags: ["deploy_tasks"] }
