---
- hosts       : all
  gather_facts: no
  become      : true
  vars_files  :
    - vars.yaml

  pre_tasks:
  - name: intall python
    raw: apt -y update && apt install -y python-minimal python-apt

  roles       :
    - install_docker
    - registry
    - deploy_tasks
