---
- hosts: all
  gather_facts: no
  vars_files:
  - vars.yaml

  tasks:
  - name: create users
    user:
      name: "{{ item.name }}"
      password: "{{ item.password | password_hash('sha512', item.sault) }}"
      shell: /usr/local/bin/dockersh
      groups: docker
      create_home: yes
    with_items: "{{ levels }}"

  - name: add custom shell in list
    lineinfile:
      path: /etc/shells
      line: /usr/local/bin/dockersh

  - name: upload custom shell
    copy:
      src: dockersh
      dest: /usr/local/bin/dockersh
      owner: root
      group: root
      mode: 0755

  - name: Create cron jobs
    cron:
      name: docker cleanup
      user: root
      job: "{{ item }}"
      cron_file: docker
    with_items:
    - "/usr/local/bin/kill-docker.sh"

  - name: upload cleanup docker script
    copy:
      src: kill-docker.sh
      dest: /usr/local/bin/kill-docker.sh
      owner: root
      group: root
      mode: 0755

  - name: check if rules file exists
    stat: 
      path: /var/tmp/addr
    register: kostyl_stat

  - name: create kostyl file
    lineinfile:
      path: /var/tmp/addr
      line: '1'
      create: yes
      mode: 0777
      state: present
    when: kostyl_stat.stat.exists == false


  #- name: upload docker config
  #  copy:
  #    src: daemon.json
  #    dest: /etc/docker/daemon.json
  #    owner: root
  #    group: root
  #    mode: 0755

  - name: upload ssh_config
    copy:
      src: ssh_config
      dest: /etc/ssh/ssh_config
      owner: root
      group: root
      mode: 0644

  - name: upload sshd_config
    copy:
      src: sshd_config
      dest: /etc/ssh/sshd_config
      owner: root
      group: root
      mode: 0644

  - name: Pull docker image
    command: docker pull {{ item.image }}
    register: docker_pull
    changed_when: "'Status: Downloaded newer image' in docker_pull.stdout"
    with_items: "{{ levels }}"
    tags:
    - pull
